FROM 304160530156.dkr.ecr.us-east-1.amazonaws.com/node:18.16.0-slim AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM 304160530156.dkr.ecr.us-east-1.amazonaws.com/node:18.16.0-slim AS production

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /app/package*.json ./

RUN npm install

COPY --from=build /app/.next /app/.next

COPY --from=build /app/public /app/public

COPY --from=build /app/scripts /app/scripts
